export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const DEVICE_SESSION_REPOSITORY = Symbol('DEVICE_SESSION_REPOSITORY');
export const AUDIT_LOG_REPOSITORY = Symbol('AUDIT_LOG_REPOSITORY');
export const SUPABASE_AUTH_CLIENT = Symbol('SUPABASE_AUTH_CLIENT');
export const AUDIT_SERVICE = Symbol('AUDIT_SERVICE');
export const RATE_LIMITER_SERVICE = Symbol('RATE_LIMITER_SERVICE');

export const FAMILY_REPOSITORY = Symbol('FAMILY_REPOSITORY');
export const FAMILY_MEMBER_REPOSITORY = Symbol('FAMILY_MEMBER_REPOSITORY');
export const FAMILY_INVITATION_REPOSITORY = Symbol(
  'FAMILY_INVITATION_REPOSITORY',
);
export const PATIENT_PROFILE_REPOSITORY = Symbol('PATIENT_PROFILE_REPOSITORY');
export const RECORD_ACCESS_GRANT_REPOSITORY = Symbol(
  'RECORD_ACCESS_GRANT_REPOSITORY',
);
export const VISIT_REPOSITORY = Symbol('VISIT_REPOSITORY');
export const DOCUMENT_REPOSITORY = Symbol('DOCUMENT_REPOSITORY');
export const STORAGE_PROVIDER = Symbol('STORAGE_PROVIDER');
export const VIRUS_SCANNER = Symbol('VIRUS_SCANNER');
export const IMAGE_CONVERTER = Symbol('IMAGE_CONVERTER');
export const METADATA_EXTRACTOR = Symbol('METADATA_EXTRACTOR');
export const DOCUMENT_QUEUE = Symbol('DOCUMENT_QUEUE');
export const DOCUMENT_PROCESSOR = Symbol('DOCUMENT_PROCESSOR');
export const EXTRACTOR_PROVIDER = Symbol('EXTRACTOR_PROVIDER');
export const TIMELINE_EVENT_REPOSITORY = Symbol('TIMELINE_EVENT_REPOSITORY');
export const PDF_GENERATOR = Symbol('PDF_GENERATOR');
export const NOTIFICATION_REPOSITORY = Symbol('NOTIFICATION_REPOSITORY');
export const OUTBOX_EVENT_REPOSITORY = Symbol('OUTBOX_EVENT_REPOSITORY');
export const EMAIL_PROVIDER = Symbol('EMAIL_PROVIDER');
export const PUSH_PROVIDER = Symbol('PUSH_PROVIDER');
