export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const DEVICE_SESSION_REPOSITORY = Symbol('DEVICE_SESSION_REPOSITORY');
export const AUDIT_LOG_REPOSITORY = Symbol('AUDIT_LOG_REPOSITORY');
export const SUPABASE_AUTH_CLIENT = Symbol('SUPABASE_AUTH_CLIENT');
export const AUDIT_SERVICE = Symbol('AUDIT_SERVICE');
export const RATE_LIMITER_SERVICE = Symbol('RATE_LIMITER_SERVICE');

export const FAMILY_REPOSITORY = Symbol('FAMILY_REPOSITORY');
export const FAMILY_MEMBER_REPOSITORY = Symbol('FAMILY_MEMBER_REPOSITORY');
export const FAMILY_INVITATION_REPOSITORY = Symbol(
  'FAMILY_INVITATION_REPOSITORY',
);
export const PATIENT_PROFILE_REPOSITORY = Symbol('PATIENT_PROFILE_REPOSITORY');
export const RECORD_ACCESS_GRANT_REPOSITORY = Symbol(
  'RECORD_ACCESS_GRANT_REPOSITORY',
);
