export class AuthError extends Error {
  constructor(
    public readonly code: string,
    message: string,
  ) {
    super(message);
    this.name = 'AuthError';
  }
}

export const AuthErrorCode = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  INVALID_OTP: 'INVALID_OTP',
  OTP_EXPIRED: 'OTP_EXPIRED',
  PASSWORD_TOO_WEAK: 'PASSWORD_TOO_WEAK',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  RATE_LIMITED: 'RATE_LIMITED',
  AUTH_PROVIDER_MISMATCH: 'AUTH_PROVIDER_MISMATCH',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  FAMILY_NOT_FOUND: 'FAMILY_NOT_FOUND',
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  INVITATION_NOT_FOUND: 'INVITATION_NOT_FOUND',
  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
  GRANT_NOT_FOUND: 'GRANT_NOT_FOUND',
  ALREADY_MEMBER: 'ALREADY_MEMBER',
  PENDING_INVITATION_EXISTS: 'PENDING_INVITATION_EXISTS',
  INVALID_INVITATION: 'INVALID_INVITATION',
  INVALID_UPLOAD: 'INVALID_UPLOAD',
  DOCUMENT_NOT_READY: 'DOCUMENT_NOT_READY',
  INVALID_ROLE: 'INVALID_ROLE',
  CANNOT_MODIFY_OWNER: 'CANNOT_MODIFY_OWNER',
  CANNOT_REMOVE_OWNER: 'CANNOT_REMOVE_OWNER',
  CANNOT_REMOVE_SELF: 'CANNOT_REMOVE_SELF',
  CANNOT_TRANSFER_OWNERSHIP: 'CANNOT_TRANSFER_OWNERSHIP',
  UNAUTHORIZED: 'UNAUTHORIZED',
} as const;
